#' List bottom-UpR warning messages and recommended actions
#'
#' Returns the package-level warning messages/patterns that can be emitted by
#' bottom-UpR itself. Dynamic fields are shown in braces. Warnings originating
#' internally from INLA are not reproduced, although bottom-UpR warnings about
#' INLA diagnostics are included.
#'
#' @return A data frame with warning identifier, category, message pattern,
#'   trigger, and suggested action.
#' @export
bottom_up_warning_catalogue <- function() {
  data.frame(
    warning_id=c(
      "coordinates_geographic","sparse_hierarchy","missing_values",
      "response_override","count_no_buildings","ppb_no_buildings",
      "adaptive_mesh_edge_order","mesh_edge_order","mesh_cutoff_large",
      "inla_cpo_failure","inla_mode_status","likelihood_nonfinite",
      "selector_no_candidates","selector_names_missing","selector_fallback",
      "cv_small_fold","cv_zero_covariates","cv_nonfinite_predictions",
      "moran_nonfinite_records","moran_no_links",
      "prediction_single_chunk","prediction_large_draw_matrix",
      "prediction_nonfinite_buildings","prediction_negative_buildings",
      "aggregation_missing_group","aggregation_nonfinite_draws",
      "simulation_small_n","simulation_single_chunk"
    ),
    category=c(
      "coordinates","hierarchy","missing_data",
      "response","response","response",
      "mesh","mesh","mesh",
      "fit","fit","likelihood",
      "selection","selection","selection",
      "cross_validation","cross_validation","cross_validation",
      "moran","moran",
      "prediction","prediction","prediction","prediction",
      "aggregation","aggregation",
      "simulation","simulation"
    ),
    message=c(
      "Coordinates appear to be longitude/latitude degrees. SPDE mesh distances, block sizes, and range priors use coordinate units; project coordinates before distance-based spatial modelling.",
      "Hierarchical effect '{column}' contains levels with fewer than {min_n} observations; posterior estimates for sparse levels may be weakly identified.",
      "Missing values detected in: {columns}. INLA/model functions may drop or fail on incomplete rows; preprocess explicitly.",
      "response_type='{requested}' overrides automatic detection ('{detected}').",
      "COUNT model has no building exposure column; the model will not include a log(buildings) offset.",
      "PPB model has no buildings column; population reconstruction from PPB will not be available automatically.",
      "Adaptive inner max_edge is not smaller than outer max_edge.",
      "Inner max_edge is not smaller than outer max_edge; check mesh settings.",
      "cutoff exceeds inner max_edge; this may over-thin input locations.",
      "INLA reported CPO failures for some observations; inspect fit$cpo$failure.",
      "INLA optimization returned a non-zero mode status; inspect fit$mode.",
      "Likelihood comparison produced non-finite mean log CPO scores.",
      "No candidate covariates supplied; selector returns an empty set.",
      "None of the candidate covariates were found in INLA fixed-effect summaries; returning all candidates.",
      "No candidate credible intervals excluded zero; applying fallback and retaining the strongest {fallback} effect(s).",
      "Some validation folds contain fewer than 3 held-out observations; metrics may be unstable.",
      "Fold {fold} selected zero covariates; fitting an intercept/spatial/hierarchical model.",
      "Non-finite held-out predictions were produced; inspect fold-level results.",
      "Non-finite held-out records are excluded from Moran's I calculation.",
      "One or more Moran distance bands contain no neighbour links.",
      "chunkwise=TRUE but chunk_size is at least nrow(newdata); prediction will use one chunk.",
      "return_draws=TRUE will allocate a large cell-by-draw matrix ({values} values). Consider return_draws=FALSE and aggregate_by= for large grids.",
      "Non-finite building exposure detected in prediction chunk; affected cells are treated as structural zeros.",
      "Negative building exposure detected in prediction data; affected cells are treated as structural zeros.",
      "Missing group labels are excluded from posterior aggregation.",
      "Non-finite posterior draw values detected; aggregate summaries may be non-finite.",
      "Small synthetic sample size; spatial and cross-validation examples may be unstable.",
      "chunkwise=TRUE but chunk_size is at least n; simulation will use one chunk."
    ),
    trigger=c(
      "Coordinate names/values look geographic in a distance-based spatial workflow.",
      "A hierarchical grouping has at least one level with fewer than 3 records.",
      "Required model/prediction columns contain NA values.",
      "Explicit response_type differs from automatic detection.",
      "COUNT response is specified without buildings.",
      "PPB response is specified without buildings.",
      "Adaptive inner_edge_fraction produces max_edge[1] >= max_edge[2].",
      "Explicit max_edge[1] >= max_edge[2].",
      "cutoff > max_edge[1].",
      "INLA returns positive CPO failure indicators.",
      "INLA returns a non-zero optimization mode status.",
      "The best automatic likelihood score is non-finite.",
      "The selector receives no candidate covariates.",
      "Candidate names cannot be matched to INLA fixed-effect summaries.",
      "No interval excludes zero and fallback > 0.",
      "At least one holdout fold has fewer than 3 rows.",
      "A fold-specific selector returns no retained covariates.",
      "Held-out prediction means contain non-finite values.",
      "Moran input contains non-finite coordinates/observed/predicted values.",
      "A requested Moran distance threshold has no neighbour links.",
      "chunkwise=TRUE and chunk_size >= nrow(newdata).",
      "nrow(newdata) * draws > 50,000,000 with return_draws=TRUE.",
      "Prediction buildings contain NA/Inf.",
      "Prediction buildings contain negative values.",
      "Aggregation group contains NA.",
      "Posterior draw matrix contains NA/Inf.",
      "Synthetic n < 50.",
      "chunkwise simulation is requested with chunk_size >= n."
    ),
    suggested_action=c(
      "Project coordinates and use matching distance units.",
      "Combine sparse levels, simplify the hierarchy, or interpret cautiously.",
      "Preprocess missing data explicitly.",
      "Confirm that the override is scientifically intended.",
      "Supply building exposure when a building-offset count model is intended.",
      "Supply buildings when population reconstruction from PPB is required.",
      "Choose inner_edge_fraction < outer_edge_fraction.",
      "Choose inner max_edge < outer max_edge.",
      "Reduce cutoff or increase inner max_edge.",
      "Inspect CPO failures and influential observations.",
      "Inspect INLA optimization diagnostics and refit if needed.",
      "Inspect candidate fits rather than relying on automatic selection.",
      "Supply candidate covariates or skip selection deliberately.",
      "Check covariate names and fixed-effect construction.",
      "Review the selector/fallback rule.",
      "Change the fold design or interpret unstable fold metrics cautiously.",
      "Confirm that a no-covariate fold model is acceptable.",
      "Inspect fold predictions and model convergence.",
      "Correct/exclude invalid held-out records.",
      "Increase thresholds or inspect sampling geometry.",
      "Reduce chunk_size to demonstrate/use multiple chunks.",
      "Use return_draws=FALSE and aggregate_by= for large grids.",
      "Correct non-finite exposure; structural-zero handling is a safeguard.",
      "Correct invalid negative exposure values.",
      "Supply complete group labels or accept exclusion.",
      "Inspect and correct the source posterior draws.",
      "Increase n for spatial/CV demonstrations.",
      "Use a smaller chunk_size."
    ),
    stringsAsFactors=FALSE
  )
}
