name: R-CMD-check

concurrency:
  group: R-CMD-check-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-pandoc@v2

      - name: Install R-INLA
        shell: Rscript {0}
        run: |
          install.packages(
            "INLA",
            repos = c(
              getOption("repos"),
              INLA = "https://inla.r-inla-download.org/R/stable"
            ),
            dependencies = TRUE
          )

      - name: Install check dependencies
        shell: Rscript {0}
        run: |
          install.packages(c("rcmdcheck", "testthat", "knitr", "rmarkdown", "roxygen2", "shiny", "leaflet"))

      - name: Generate documentation
        shell: Rscript {0}
        run: |
          roxygen2::roxygenise()

      - name: R CMD check
        shell: Rscript {0}
        run: |
          rcmdcheck::rcmdcheck(
            args = c("--no-manual", "--as-cran"),
            error_on = "warning",
            check_dir = "check"
          )
